from __future__ import annotations

import uuid
from datetime import datetime, timezone
from pathlib import Path

from fastapi import APIRouter, BackgroundTasks, Depends, HTTPException
from fastapi.responses import FileResponse
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.security import get_current_user_id
from app.database import get_db, get_db_context
from app.models.application import Application
from app.models.job import Job
from app.models.resume import Resume
from app.schemas import ApplicationOut, ApprovalAction
from app.core.logging import get_logger
from app.services.apply_service import ApplyInput, resolve_contact_email, submit_application

router = APIRouter(prefix="/applications", tags=["applications"])
logger = get_logger(__name__)


from sqlalchemy.orm import selectinload

@router.get("/", response_model=list[ApplicationOut])
async def list_applications(
    status: str | None = None,
    user_id: uuid.UUID = Depends(get_current_user_id),
    db: AsyncSession = Depends(get_db),
):
    query = (
        select(Application)
        .options(selectinload(Application.job))
        .where(Application.user_id == user_id)
        .order_by(Application.created_at.desc())
    )
    if status:
        query = query.where(Application.status == status)
    result = await db.execute(query)
    return result.scalars().all()


@router.get("/pending", response_model=list[ApplicationOut])
async def list_pending_approvals(
    user_id: uuid.UUID = Depends(get_current_user_id),
    db: AsyncSession = Depends(get_db),
):
    result = await db.execute(
        select(Application)
        .options(selectinload(Application.job))
        .where(Application.user_id == user_id, Application.status == "pending_approval")
        .order_by(Application.created_at.desc())
    )
    return result.scalars().all()


@router.get("/stats", response_model=dict)
async def get_stats(
    user_id: uuid.UUID = Depends(get_current_user_id),
    db: AsyncSession = Depends(get_db),
):
    result = await db.execute(select(Application).where(Application.user_id == user_id))
    apps = result.scalars().all()
    return {
        "total": len(apps),
        "pending_approval": sum(1 for a in apps if a.status == "pending_approval"),
        "approved": sum(1 for a in apps if a.status == "approved"),
        "submitted": sum(1 for a in apps if a.status == "submitted"),
        "needs_manual_review": sum(1 for a in apps if a.status == "needs_manual_review"),
        "failed": sum(1 for a in apps if a.status == "failed"),
        "rejected": sum(1 for a in apps if a.status == "rejected"),
    }


@router.get("/{application_id}", response_model=ApplicationOut)
async def get_application(
    application_id: uuid.UUID,
    user_id: uuid.UUID = Depends(get_current_user_id),
    db: AsyncSession = Depends(get_db),
):
    result = await db.execute(
        select(Application)
        .options(selectinload(Application.job))
        .where(Application.id == application_id, Application.user_id == user_id)
    )
    app = result.scalar_one_or_none()
    if not app:
        raise HTTPException(status_code=404, detail="Application not found")
    return app


@router.get("/{application_id}/resume/download")
async def download_updated_resume(
    application_id: uuid.UUID,
    user_id: uuid.UUID = Depends(get_current_user_id),
    db: AsyncSession = Depends(get_db),
):
    """Download the actual latest tailored resume generated by the resume
    tailoring agent for this application (Application.tailored_resume_path)
    — never the original uploaded resume, and never stale data, since this
    reads the path directly off the application record each request.
    """
    result = await db.execute(
        select(Application).where(Application.id == application_id, Application.user_id == user_id)
    )
    app = result.scalar_one_or_none()
    if not app:
        raise HTTPException(status_code=404, detail="Application not found")
    if not app.tailored_resume_path:
        raise HTTPException(status_code=404, detail="No updated resume has been generated for this application yet")

    path = Path(app.tailored_resume_path)
    if not path.exists():
        raise HTTPException(status_code=404, detail="Updated resume file is missing on the server")

    suffix = path.suffix or ".txt"
    return FileResponse(
        path=str(path),
        filename=f"updated_resume_{application_id}{suffix}",
        media_type="text/plain" if suffix == ".txt" else "application/octet-stream",
    )


@router.post("/{application_id}/approve", response_model=dict)
async def approve_application(
    application_id: uuid.UUID,
    payload: ApprovalAction,
    background_tasks: BackgroundTasks,
    user_id: uuid.UUID = Depends(get_current_user_id),
    db: AsyncSession = Depends(get_db),
):
    result = await db.execute(
        select(Application).where(Application.id == application_id, Application.user_id == user_id)
    )
    app = result.scalar_one_or_none()
    if not app:
        raise HTTPException(status_code=404, detail="Application not found")
    if app.status not in ("pending_approval", "approved"):
        raise HTTPException(status_code=409, detail=f"Application is '{app.status}', cannot approve")

    if payload.decision == "approve":
        app.status = "approved"
        app.approved_at = datetime.now(timezone.utc)
        app.reviewer_notes = payload.edit_instructions
        await db.commit()
        background_tasks.add_task(_submit_application_background, str(application_id), str(user_id))
        return {
            "status": "approved",
            "message": "Approved. Attempting submission — check status shortly. Verify via screenshot before trusting it went through.",
            "application_id": str(application_id),
        }
    else:
        app.status = "rejected"
        app.reviewer_notes = payload.edit_instructions
        await db.commit()
        return {"status": "rejected", "message": "Application rejected."}


@router.post("/approve-all", response_model=dict)
async def approve_all_pending(
    background_tasks: BackgroundTasks,
    user_id: uuid.UUID = Depends(get_current_user_id),
    db: AsyncSession = Depends(get_db),
):
    result = await db.execute(
        select(Application).where(Application.user_id == user_id, Application.status == "pending_approval")
    )
    apps = result.scalars().all()
    if not apps:
        return {"message": "No pending applications", "count": 0}

    app_ids = []
    for app in apps:
        app.status = "approved"
        app.approved_at = datetime.now(timezone.utc)
        app_ids.append(str(app.id))
    await db.commit()

    for app_id in app_ids:
        background_tasks.add_task(_submit_application_background, app_id, str(user_id))

    return {"message": f"Approved {len(app_ids)} applications.", "count": len(app_ids), "application_ids": app_ids}


@router.post("/submit-approved", response_model=dict)
async def submit_all_approved(
    background_tasks: BackgroundTasks,
    user_id: uuid.UUID = Depends(get_current_user_id),
    db: AsyncSession = Depends(get_db),
):
    result = await db.execute(
        select(Application).where(Application.user_id == user_id, Application.status == "approved")
    )
    apps = result.scalars().all()
    if not apps:
        return {"message": "No approved applications waiting", "count": 0}

    for app in apps:
        background_tasks.add_task(_submit_application_background, str(app.id), str(user_id))

    return {"message": f"Attempting {len(apps)} submissions in background.", "count": len(apps)}


@router.post("/{application_id}/mark-manual-applied", response_model=dict)
async def mark_manually_applied(
    application_id: uuid.UUID,
    user_id: uuid.UUID = Depends(get_current_user_id),
    db: AsyncSession = Depends(get_db),
):
    """Use this AFTER you've manually applied yourself and confirmed it on the portal."""
    result = await db.execute(
        select(Application).where(Application.id == application_id, Application.user_id == user_id)
    )
    app = result.scalar_one_or_none()
    if not app:
        raise HTTPException(status_code=404, detail="Application not found")
    app.status = "submitted"
    app.confirmation_number = "MANUAL-CONFIRMED"
    app.applied_at = datetime.now(timezone.utc)
    await db.commit()
    return {"status": "submitted", "message": "Marked as manually confirmed applied."}


# ─── Background submission with HONEST verification ──────────────────────────
# Delegates entirely to app/services/apply_service.py — see that module for
# the actual Playwright automation, login verification, resume upload,
# required-field validation, and success-confirmation logic. This file only
# assembles the ApplyInput from the DB and persists the ApplyResult back.

async def _submit_application_background(application_id: str, user_id: str) -> None:
    logger.info("Background submission started", extra={"app_id": application_id})
    try:
        async with get_db_context() as db:
            result = await db.execute(select(Application).where(Application.id == uuid.UUID(application_id)))
            app = result.scalar_one_or_none()
            if not app:
                return
            job_result = await db.execute(select(Job).where(Job.id == app.job_id))
            job = job_result.scalar_one_or_none()
            resume_result = await db.execute(select(Resume).where(Resume.id == app.resume_id))
            resume = resume_result.scalar_one_or_none()

        if not job:
            await _update_result(application_id, "failed", error="Job not found in database")
            return

        contact_info = resume.contact_info if resume and resume.contact_info else {}
        # Resume-extracted email may be missing — fall back to the
        # authenticated user's verified account email. See
        # resolve_contact_email() docstring for the exact priority rules;
        # it never overwrites a valid resume-extracted email.
        contact_info = await resolve_contact_email(contact_info, user_id)

        cover_letter = ""
        if app.cover_letter_path:
            try:
                cover_letter = Path(app.cover_letter_path).read_text(encoding="utf-8")
            except Exception:
                pass

        apply_input = ApplyInput(
            application_id=application_id,
            job_url=job.url,
            portal=(job.portal or "unknown").lower(),
            user_id=user_id,
            contact_info=contact_info,
            cover_letter=cover_letter,
            resume_file_path=getattr(resume, "file_path", None) if resume else None,
            job_context=job.description or "",
        )
        result = await submit_application(apply_input)
        
        await _update_result(
            application_id,
            result.status,
            confirmation=result.confirmation_number,
            error=result.error_message,
            screenshot=result.screenshot_path,
        )

        from app.services.notification_service import get_notification_service
        notif = get_notification_service()

        if result.status == "submitted":
            await notif.notify_application_submitted(
                job_title=job.title, company=job.company,
                confirmation=result.confirmation_number or "Verified on page",
            )
        elif result.status == "needs_manual_review":
            await notif.send_email(
                subject=f"⚠️ Needs your review: {job.title} at {job.company}",
                body=f"""
                <h2>Could not confirm automatic submission</h2>
                <p><strong>{job.title}</strong> at <strong>{job.company}</strong></p>
                <p>Reason: {result.error_message or 'No success confirmation detected on page'}</p>
                <p>This usually means the form requires login, has a custom layout, or needs a CAPTCHA.</p>
                <p><strong>Please apply manually:</strong> <a href="{job.url}">{job.url}</a></p>
                <p>A screenshot of what the bot saw is saved on your server for reference.</p>
                """,
            )
        else:
            await notif.notify_application_failed(
                job_title=job.title, company=job.company,
                error=result.error_message or "Unknown error",
            )

    except Exception as e:
            import traceback
            full_error = traceback.format_exc()
            print("\n=== REAL SUBMISSION FAILURE TRACEBACK ===")
            print(full_error)
            print("=== END TRACEBACK ===\n")
            logger.error("Application submission failed", extra={"full_traceback": full_error})
            await _update_result(application_id, "failed", error=f"Unhandled error: {e!r}")
        

async def _update_result(application_id: str, status: str, confirmation: str | None = None,
                          error: str | None = None, screenshot: str | None = None) -> None:
    try:
        async with get_db_context() as db:
            result = await db.execute(select(Application).where(Application.id == uuid.UUID(application_id)))
            app = result.scalar_one_or_none()
            if app:
                app.status = status
                app.confirmation_number = confirmation
                app.error_message = error
                if screenshot:
                    app.confirmation_screenshot_path = screenshot
                if status == "submitted":
                    app.applied_at = datetime.now(timezone.utc)
    except Exception as e:
        logger.error("Failed to update application result", extra={"error": str(e)})