"""add job matching fields

Revision ID: 3f96a57880e5
Revises: 
Create Date: 2026-08-15 12:06:50.035182
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f96a57880e5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('match_score', sa.Float(), nullable=True))
    op.add_column('jobs', sa.Column('match_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('jobs', sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_jobs_last_seen_at', 'jobs', ['last_seen_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_jobs_last_seen_at', table_name='jobs')
    op.drop_column('jobs', 'last_seen_at')
    op.drop_column('jobs', 'match_reasons')
    op.drop_column('jobs', 'match_score')
    # ### end Alembic commands ###